// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create short URL from original URL
	// (POST /)
	CreateShortURL(w http.ResponseWriter, r *http.Request)
	// Redirect from short URL to original URL
	// (GET /{short-url})
	RedirectURL(w http.ResponseWriter, r *http.Request, shortUrl string)
	// Get stats about redirects
	// (GET /{short-url}/stats)
	GetStats(w http.ResponseWriter, r *http.Request, shortUrl string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// CreateShortURL operation middleware
func (siw *ServerInterfaceWrapper) CreateShortURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShortURL(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// RedirectURL operation middleware
func (siw *ServerInterfaceWrapper) RedirectURL(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "short-url" -------------
	var shortUrl string

	err = runtime.BindStyledParameter("simple", false, "short-url", chi.URLParam(r, "short-url"), &shortUrl)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter short-url: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectURL(w, r, shortUrl)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "short-url" -------------
	var shortUrl string

	err = runtime.BindStyledParameter("simple", false, "short-url", chi.URLParam(r, "short-url"), &shortUrl)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter short-url: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, shortUrl)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/", wrapper.CreateShortURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{short-url}", wrapper.RedirectURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{short-url}/stats", wrapper.GetStats)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUy27bMBD8FWLbo2Ipj/agUx+HIEAOhY2cWh9oaq0wlUh1uQoQGP73YklLdmyhSNu0",
	"J9Pk7s5wZqgNGN923qHjAOUGgrnHVsflHH/0GPhufiv/OvIdEluMZz018rP21GqGMv7PgJ86hBICk3U1",
	"bLfjjl89oGHYZjDH0HkXcHJquPc04P16dAaBNYcX1U7RWEj3KQHXt3OsLKFJp+Ng6/j91X60dYw1UuTx",
	"Ys6nPGTLurWXXuMda8OyxFbbBkrQDX43iKsPtWzMjG8FsMJgyHZsvYMS7ua3aiEU0CGpj19uvoEgW25w",
	"6hQyeEQKqfd8VswKGek7dLqzUMLlrJidQwad5vuoQB5F8iESE6m0AN9UUMJnQs24GO6fAaXAfPLV03Aj",
	"dLFRd11jTWzNH4KAD0mT1VvCNZTwJt9HMd/lMD8IYZRLMCxhBSVTj3EjBSqyvSjOXxF5n9QI/Vz46Lvq",
	"qVEm6lCJkFdFIWOfV650pXbSSM27qRoJFDndqID0iKSQyFOMTOjbVtPTqLdKwOLsmnyrPNnaSmfygHUd",
	"oPwKi6EKljIl38S2s56araDXOGHoEP00qdOkW2QkmbeZvH0k4UnRrlFiLomGMgYIMnC6xaH8LL2K5w5m",
	"B24cv5flkbuXxeWpcqE3BkNY940ab5OsuDotdp7V2veu+isjBp2SAXsp2P+BG3kYPkWTnlwjp2/VbxlS",
	"I4sZozEq7Gb8M28ukpiv8vLShafe3P/3+hp34im98j2PioZDdyPfZSS82zuGOn67e/n30dhmx10j+EF5",
	"0ma5/RkAAP//AAWjF7kHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
